### PR TITLE
Custom Smudges

### PR DESCRIPTION
**Pull request by Dzierzan**
I only added pngsheet to the bits folder, no actual yaml changes.

Here's a mockup picture
unknown

### CODE REVIEW

**Comment by Mailaender** [comment]
Tried to get them to work https://github.com/Mailaender/OpenHV/tree/smudges but no luck so far.

**Comment by GraionDilach** [comment]
Let me try. I'm interested. I don't think this needs a split from what it is now.

**Comment by GraionDilach** [comment]
https://github.com/GraionDilach/OpenHV/tree/smudges is working. I had to fixup the `smudges.png` from here since it is 199x18 instead of the expected 200x20. I didn't cut the file up though, felt no need for that one.

**Comment by Mailaender** [comment]
I forgot to add `AcceptsSmudges` in the tileset. It currently crashes as it does not like smudges with multiple stages together with ones that have fewer I guess:

```
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Graphics.Animation..ctor (OpenRA.World world, System.String name, System.Func`1[TResult] facingFunc, System.Func`1[TResult] paused) [0x00041] in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Graphics/Animation.cs:47 
  at OpenRA.Graphics.Animation..ctor (OpenRA.World world, System.String name, System.Func`1[TResult] facingFunc) [0x00000] in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Graphics/Animation.cs:39 
  at OpenRA.Mods.Common.Effects.SpriteEffect..ctor (System.Func`1[TResult] posFunc, System.Func`1[TResult] facingFunc, OpenRA.World world, System.String image, System.String sequence, System.String palette, System.Boolean visibleThroughFog, System.Int32 delay) [0x00040] in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Mods.Common/Effects/SpriteEffect.cs:51 
  at OpenRA.Mods.Common.Effects.SpriteEffect..ctor (OpenRA.WPos pos, OpenRA.World world, System.String image, System.String sequence, System.String palette, System.Boolean visibleThroughFog, System.Int32 facing, System.Int32 delay) [0x00015] in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Mods.Common/Effects/SpriteEffect.cs:35 
  at OpenRA.Mods.Common.Traits.SmudgeLayer+<>c__DisplayClass10_0.<AddSmudge>b__0 (OpenRA.World w) [0x00000] in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Mods.Common/Traits/World/SmudgeLayer.cs:151 
  at OpenRA.World.Tick () [0x0019e] in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/World.cs:470 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x001bc] in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Game.cs:602 
  at OpenRA.Game.LogicTick () [0x0003e] in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Game.cs:629 
  at OpenRA.Game.Loop () [0x000f1] in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Game.cs:793 
  at OpenRA.Game.Run () [0x0003c] in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Game.cs:834 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00010] in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Game.cs:263 
  at OpenRA.Program.Main (System.String[] args) [0x00044] in /home/matthias/Entwicklung/OpenHV/engine/OpenRA.Game/Support/Program.cs:37
```

**Comment by GraionDilach** [comment]
That's coming from the default `SmokeChance` being set to 25% and OpenHV lacking smoke_m/idle to be able to spawn it.

**Comment by Dzierzan** [comment]
Set the smoke to - 1

**Comment by Mailaender** [comment]
Thanks to both of you. Now it works properly.

**Pull request closed without merging**
