### PR TITLE
Remapped flag

### PR DESCRIPTION
**Pull request by Dzierzan**

### CODE REVIEW

**Comment by Dzierzan** [comment]
But you can update FrameSize (39,52) in yaml file which should fix the problem

**Comment by Mailaender** [comment]
Your flag is W: 84px | H: 20px not 80x20.

**Comment by Dzierzan** [comment]
Sorry, you're right. It should be 17x20 per frame.

**Comment by Mailaender** [comment]
That would be 85px then, but the file is only 84px.

**Comment by GraionDilach** [comment]
Related question: why the shadows were dropped from the flag anyway? The original sprite in HV included shadows.

**Comment by Mailaender** [comment]
Not all units have shadows and the offsets don't look quite right on first sight so I skipped them for now. Might add them later.

**Comment by Mailaender** [comment]
https://github.com/Mailaender/OpenHV/commit/fb39752ae80a3a6c85dfd941363930ee9fd1bfdc I kept it 20x20 px as my existing offset calculations depend on it.

**Pull request closed without merging**
