### PR TITLE
Add some CC 3.0 license sounds

### PR DESCRIPTION
**Pull request by Dzierzan**
Added some sounds from soundbible website. All authors are credited in README.md

### CODE REVIEW

**Comment by GraionDilach** [comment]
Could you please change the folder setup? Spaces in the path are probably a bad idea.  #4 provides some ideas.

**Comment by GraionDilach** [comment]
Sorry, but when I meant spaces in path, I also meant spaces in file names.

**Comment by GraionDilach** [comment]
I'll try to go through these during tonight. Might file a PR against your PR - I have filed all sounds to this repository with a shared volume setting so far (GoldWave's Normalize Volume to -16 dB) which sounds like an idea to do here as well.

I probably should document those above settings anyway.

**Comment by GraionDilach** [comment]
These sound way more professional than what I'd expect being released as CC-BY. Tomorrow I'll recheck their sources on that SoundBible one-by-one. Sorry, but these sound suspicious on first hear.

They are also huge anyway and need to be downsampled. I went with 22kHz IMA mono in the other PR because variants of that format was very common back during 1995-1999.

**Comment by Dzierzan** [comment]
I edited them too by cutting too long parts or speeding up the tempo (missile one). You can check if their license is correct. Besides classic graphics do not mean you are forced to use 22kHz.

**Comment by GraionDilach** [comment]
> do not mean you are forced to use 22kHz

https://github.com/OpenRA/OpenRA/issues/14153 is still an issue and it can either be based upon the amount of channels utilized or the amount of data required to be puffered. Since the exact cause of it is still unknown, it's better to play safe and prevent wasting 800 kB in the sound puffer for a single sound effect if you can decrease that to ~20 kB first.

Additionally, sound quality should remain consistent among all the samples used, considering the visuals seem to achieve a fairly consistent style so far.

I don't see any reason why not to go with 22 kHz mono as the standard. The entire pre-C&C3 C&C modding community has no issue with that format, even when this "degrades" voice actors who ventured to/came from non-union professional works (Gabriel Wolf, who was a prominent voice actor at Star Trek Online before it went to union voiced a good portion of Mental Omega 3.0, not to mention George "Seóras" Exley and Ki "ComradeCrimson" McKenzie whom kickstarted their career from C&C/Warhammer 40k mod roles, notably Rise of the Reds). I will not deny that there is indeed a minor fidelity loss with the downsampling, but I don't think that difference can be audible ingame.

**Comment by Dzierzan** [comment]
I didn't know such details though. If it's a must to use 22kHz, then so be it.

**Comment by GraionDilach** [comment]
Superseded by #42.

**Comment by Mailaender** [comment]
Not a fan of adding all those unused sounds, but okay.

**Pull request closed without merging**
