### PR TITLE
Beast

### PR DESCRIPTION
**Pull request by Dzierzan**
critter

Basic implementation of beast critter. Added CC-BY-3.0 license sounds for it. Death sequence is custom made by me.

### CODE REVIEW

**Comment by Mailaender** [comment]
Where did you download the sounds?

**Comment by GraionDilach** [comment]
Judging by the naming, it's from SoundBible again.

**Comment by Mailaender** [comment]
Can you provide the links for the record?

**Comment by Dzierzan** [comment]
Let me improve that.

**Comment by Dzierzan** [comment]
Does it have to be noted the sounds were altered by me (increased tempo)?

**Comment by GraionDilach** [comment]
Are these sounds 22kHz mono IMA? Their filesizes look huge. Personally, I'd skip the sounds and only take the graphic for now (they prolly also need volume normalization to fit with everything else).

**Comment by Dzierzan** [comment]
They are 22kHz and mono.

**Pull request merged**
