### PR TITLE
Remapped Generator

### PR DESCRIPTION
**Pull request by Dzierzan**

### CODE REVIEW

**Comment by Dzierzan** [comment]
Yeah, I just made it more "compact". The FramSize has to be updated which is 39,52. I should have updated yaml file as well.

**Comment by Mailaender** [comment]
639 / 40 = 15,975 px so that won't, too.

**Comment by Dzierzan** [comment]
Check the generator now.

**Comment by Mailaender** [comment]
https://github.com/Mailaender/OpenHV/commit/e6e44231d82569694a448f663fd547d0946dcbf2

**Pull request closed without merging**
